title: "Masami Hashiguchi Portfolio"
description: "ポートフォリオサイト"

url: "https://hashiguchimasami.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

author:
  name: "Masami Hashiguchi"
  bio: "Portfolio"

author:
  name: "Masami Hashiguchi"
  avatar: "/assets/images/avatar.jpg"
  bio: "Designer / Portfolio"

minimal_mistakes_skin: "air" # 見た目変更（他：mint, contrast など）

